<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: chat.proto

namespace Chat;

use Spiral\RoadRunner\GRPC;

interface ChatServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "chat.ChatService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message $in
    * @return Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SayHello(GRPC\ContextInterface $ctx, Message $in): Message;
}
